# Generated by Django 5.1.1 on 2025-01-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0003_post_created_at_alter_post_image_alter_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
